'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useParams, useRouter } from 'next/navigation';
import { ArrowLeft, BookmarkPlus, Check, Clock3, Flame, Plus, Star } from 'lucide-react';
import { getWorkout } from '@/lib/api';
import { useStore } from '@/lib/store';
import type { Workout } from '@/types/workout';
export default function WorkoutDetailPage(){const params=useParams<{id:string}>();const router=useRouter();const id=Number(params.id);const [workout,setWorkout]=useState<Workout|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');const {plan,saved,addPlan,save}=useStore();
useEffect(()=>{let alive=true;if(!Number.isInteger(id)||id<=0){setError('This workout could not be found.');setLoading(false);return;}getWorkout(id).then(w=>{if(alive){if(w)setWorkout(w);else setError('This workout could not be found.')}}).catch(e=>{if(alive)setError(e instanceof Error?e.message:'Unable to load workout details.')}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[id]);
if(loading)return <div className="detail-state"><div className="spinner"/><p>Loading workout…</p></div>;
if(error||!workout)return <div className="detail-state"><div className="state-icon">404</div><h2>WORKOUT NOT FOUND</h2><p>{error||'This workout is no longer available.'}</p><Link className="button button-primary" href="/">Back to library</Link></div>;
const inPlan=plan.some(w=>w.id===workout.id),isSaved=saved.some(w=>w.id===workout.id),full=plan.length>=5&&!inPlan;
return <section className="detail-page section-shell"><Link href="/#library" className="back-link"><ArrowLeft size={16}/> BACK TO LIBRARY</Link><div className="detail-layout"><div className="detail-visual"><div className="detail-visual-label"><span className="live-dot"/> MOVEMENT / {String(workout.id).padStart(2,'0')}</div>{workout.image?<img src={workout.image} alt={workout.name} onError={e=>{e.currentTarget.style.display='none';e.currentTarget.parentElement?.classList.add('image-missing')}}/>:<div className="detail-fallback"><span>FITLOG</span><b>{workout.name}</b></div>}<div className="visual-caption"><span>FORM FIRST.</span><span>PROGRESS FOLLOWS.</span></div></div><div className="detail-content"><div className="eyebrow"><span/> WORKOUT DETAILS</div><h1>{workout.name}</h1><p className="detail-description">{workout.description}</p><div className="tag-row detail-tags">{workout.muscleGroups.map(tag=><span className="tag" key={tag}>{tag}</span>)}</div><div className="spec-panel"><div className="spec-heading">KEY SPECS <span>● LIVE DATA</span></div><div className="spec-grid">{[['EQUIPMENT',workout.equipment],['DIFFICULTY',workout.difficulty],['SETS',String(workout.sets)],['REPS',workout.reps],['DURATION',`${workout.duration} min`],['CALORIES',`${workout.caloriesBurned} kcal`],['RATING',workout.rating.toFixed(1)]].map(([label,value])=><div className="spec-row" key={label}><span>{label}</span><b>{value}</b></div>)}</div></div><div className="instructions"><div className="spec-heading">INSTRUCTIONS <span>{workout.instructions.length||4} STEPS</span></div>{(workout.instructions.length?workout.instructions:['Set up your equipment and check your form.','Brace your core and begin the movement with control.','Complete each repetition through a comfortable range of motion.','Return to the starting position and reset before the next rep.']).slice(0,4).map((step,i)=><div className="instruction" key={`${i}-${step}`}><span>{String(i+1).padStart(2,'0')}</span><p>{step}</p></div>)}</div><div className="detail-actions"><button className="button button-primary" onClick={()=>{if(!inPlan&&!full)addPlan(workout);else if(full) addPlan(workout);}} disabled={full||inPlan}><Plus size={17}/>{inPlan?'IN TODAY’S PLAN':full?'PLAN IS FULL':"ADD TO TODAY'S PLAN"}</button><button className={`button button-outline ${isSaved?'is-saved':''}`} onClick={()=>save(workout)}><BookmarkPlus size={17}/>{isSaved?'SAVED FOR LATER':'SAVE FOR LATER'}</button></div>{full&&<p className="limit-note"><Check size={14}/> Your plan is capped at five workouts. Remove one to add another.</p>}</div></div></section>}
