'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { Check, Clock3, Flame, Search, Star, Trash2, ArrowUpRight, Dumbbell } from 'lucide-react';
import { useStore } from '@/lib/store';
import type { Workout } from '@/types/workout';
function PlanCard({workout,savedTab,done,onRemove,onDone}:{workout:Workout;savedTab:boolean;done:boolean;onRemove:()=>void;onDone:()=>void}){return <article className={`plan-card ${done?'completed':''}`}><Link href={`/workout/${workout.id}`} className="plan-thumb">{workout.image?<img src={workout.image} alt={workout.name} onError={e=>{e.currentTarget.style.display='none';e.currentTarget.parentElement?.classList.add('image-missing')}}/>:<Dumbbell size={26}/>}</Link><div className="plan-card-main"><div className="tag-row">{(workout.muscleGroups||[]).slice(0,2).map(t=><span className="tag" key={t}>{t}</span>)}</div><h3>{workout.name}</h3><p>{workout.equipment}</p><div className="stats-row"><span><Clock3 size={14}/>{workout.duration} min</span><span><Flame size={14}/>{workout.caloriesBurned} kcal</span><span><Star size={14}/>{workout.rating.toFixed(1)}</span></div></div><div className="plan-card-actions"><Link href={`/workout/${workout.id}`} className="button button-outline small-button">VIEW DETAILS <ArrowUpRight size={14}/></Link>{!savedTab&&<button className={`button ${done?'button-done':'button-primary'} small-button`} onClick={onDone}><Check size={14}/>{done?'DONE':'MARK AS DONE'}</button>}<button className="icon-button remove-button" onClick={onRemove} aria-label={`Remove ${workout.name}`}><Trash2 size={16}/></button></div></article>}
export default function MyPlanPage(){const {plan,saved,done,ready,removePlan,removeSaved,toggleDone}=useStore();const [tab,setTab]=useState<'plan'|'saved'>('plan'),[query,setQuery]=useState(''),[sort,setSort]=useState('duration');useEffect(()=>{if(new URLSearchParams(window.location.search).get('tab')==='saved')setTab('saved')},[]);const list=tab==='plan'?plan:saved;const filtered=useMemo(()=>list.filter(w=>`${w.name} ${w.equipment} ${w.muscleGroups.join(' ')}`.toLowerCase().includes(query.toLowerCase())).slice().sort((a,b)=>sort==='calories'?b.caloriesBurned-a.caloriesBurned:sort==='rating'?b.rating-a.rating:a.duration-b.duration),[list,query,sort]);const minutes=plan.reduce((s,w)=>s+w.duration,0),calories=plan.reduce((s,w)=>s+w.caloriesBurned,0);
return <section className="plan-page section-shell"><div className="plan-heading"><div><div className="eyebrow"><span/> YOUR TRAINING LOG</div><h1>MY <span>PLAN</span></h1><p>Cap of five lifts for today. Finish them, then load more.</p></div><div className="plan-cap"><span className="cap-icon"><Dumbbell size={18}/></span><div><b>{plan.length}<i>/ 5</i></b><small>DAILY CAPACITY</small></div><div className="cap-bars">{[0,1,2,3,4].map(i=><span className={i<plan.length?'filled':''} key={i}/>)}</div></div></div>
<div className="metrics-grid"><div className="metric-card"><span>EXERCISES</span><div><b>{plan.length.toString().padStart(2,'0')}</b><span className="metric-icon"><Dumbbell size={19}/></span></div><small>IN TODAY&apos;S PLAN</small></div><div className="metric-card"><span>TOTAL MINUTES</span><div><b>{minutes.toString().padStart(2,'0')}</b><span className="metric-icon"><Clock3 size={19}/></span></div><small>ESTIMATED DURATION</small></div><div className="metric-card"><span>CALORIES</span><div><b>{calories.toLocaleString()}</b><span className="metric-icon"><Flame size={19}/></span></div><small>ESTIMATED BURN</small></div></div>
<div className="plan-list-header"><div className="tabs" role="tablist"><button className={tab==='plan'?'tab active':'tab'} onClick={()=>setTab('plan')} role="tab" aria-selected={tab==='plan'}>TODAY&apos;S PLAN <span>{plan.length}</span></button><button className={tab==='saved'?'tab active':'tab'} onClick={()=>setTab('saved')} role="tab" aria-selected={tab==='saved'}>SAVED <span>{saved.length}</span></button></div><div className="library-tools plan-tools"><label className="search-box"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search your list" aria-label="Search your plan"/></label><label className="sort-select"><span>SORT</span><select value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sort plan"><option value="duration">Duration</option><option value="calories">Calories</option><option value="rating">Rating</option></select></label></div></div>
{!ready?<div className="plan-loading"><div className="spinner"/>Loading workouts…</div>:filtered.length===0?<div className="empty-state"><div className="empty-symbol"><Dumbbell size={28}/></div><div className="eyebrow"><span/> THE NEXT REP IS YOURS</div><h2>NOTHING <em>HERE</em> YET</h2><p>Browse the library and add a lift to get today moving.</p><Link href="/" className="button button-primary">GO TO WORKOUTS <ArrowUpRight size={16}/></Link></div>:<div className="plan-cards">{filtered.map(w=><PlanCard key={w.id} workout={w} savedTab={tab==='saved'} done={done.includes(w.id)} onRemove={()=>tab==='plan'?removePlan(w.id):removeSaved(w.id)} onDone={()=>toggleDone(w.id)}/>)}</div>}
<div className="plan-bottom"><span>TRAIN WITH INTENT. LOG EVERY SET.</span><span>{filtered.length} {filtered.length===1?'MOVEMENT':'MOVEMENTS'} DISPLAYED</span></div></section>}
